### ISSUE TITLE
Broken build with 7.2.0-dev

### ISSUE THREAD

**Issue by remicollet** [laruence/yaconf#27]
Only a tracker (7.2.0 is really not close to release ;)

```
/dev/shm/BUILD/php72-php-pecl-yaconf-1.0.5/NTS/yaconf.c: In function 'php_yaconf_hash_init':
/dev/shm/BUILD/php72-php-pecl-yaconf-1.0.5/NTS/yaconf.c:95:23: error: 'IS_TYPE_IMMUTABLE' undeclared (first use in this function)
  Z_TYPE_FLAGS_P(zv) = IS_TYPE_IMMUTABLE;
                       ^~~~~~~~~~~~~~~~~
/dev/shm/BUILD/php72-php-pecl-yaconf-1.0.5/NTS/yaconf.c:95:23: note: each undeclared identifier is reported only once for each function it appears in
/dev/shm/BUILD/php72-php-pecl-yaconf-1.0.5/NTS/yaconf.c: In function 'zm_startup_yaconf':
/dev/shm/BUILD/php72-php-pecl-yaconf-1.0.5/NTS/yaconf.c:503:18: warning: unused variable 'c' [-Wunused-variable]
    unsigned char c;
                  ^
Makefile:194: recipe for target 'yaconf.lo' failed

```

**Comment by laruence** [comment]
this should already be fixed
